CLASS zcl_03_handler_2 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC FOR EVENTS OF Z03_R_Travel.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_03_handler_2 IMPLEMENTATION.
ENDCLASS.
